### PR TITLE
xe: fix locale handling

### LINKED ISSUE #3181: Does oneDNN has locale limitations?
Hi, oneDNN developers

I am using OpenVINO2025.1 to do dGPU (A770) inference, but I found if I set:
 std::locale::global(std::locale("chs"));
or
 std::locale::global(std::locale("En_US"));
or
 std::locale::global(std::locale(""));
The inference will crash on oneDNN, but If I removed the locale set, the inference will be fine.
This is part of the crash log:

> 1:153:23: note: expanded from macro '\
> CONCAT2'
> #define CONCAT2(a, b) CONCAt2(a, b)
>                       ^
> note: (skipping 7 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
> 1:152:23: note: expanded from macro 'CONCAt2'
> #define CONCAt2(a, b) a##b
>                       ^
> <scratch space>:213:1: note: expanded from here
> PO_0_ELTWISE_SCALE
> ^
> <command line>:329:29: note: expanded from here
> #define  PO_0_ELTWISE_SCALE as_float(0x3f,800,000)
>                             ^
> 1:12553:18: warning: left operand of comma operator has no effect
> const off_t oh = GWS_GET_OH();
>                  ^~~~~~~~~~~~
> <command line>:27:21: note: expanded from here
> #define  GWS_GET_OH GWS0_GET_ID2
>                     ^
> 1:887:63: note: expanded from macro 'GWS0_GET_ID2'
> #define GWS0_GET_ID2() GWS0_OP2(GWS_GET_THREAD_ID(GWS0_IDX2), GWS0_STRIDE2, div_up(GWS0_DIM2, GWS0_BLOCK2)) / GWS0_VEC_SIZE2 * GWS0_VEC_SIZE2 * GWS0_BLOCK2
>                                                               ^~~~~~~~~~~~
> <command line>:145:23: note: expanded from here
> #define  GWS0_STRIDE2 4,608
>                       ^
> 1:884:48: note: expanded from macro 'GWS_OP_MOD'
> #define GWS_OP_MOD(idx, stride, max) ((idx) / (stride) % (max))
>                                                ^~~~~~
> ,src\gpu\intel\ocl\engine.cpp:174
> onednn_verbose,v1,primitive,error,ocl,errcode -11,CL_BUILD_PROGRAM_FAILURE,src\gpu\intel\ocl\engine.cpp:278,src\gpu\intel\ocl\engine.cpp:278

Just want to know how can I fix this, I have to set the locale because I have a lot of chinese logs in the appliation, and without locale set, the log will be unreadable. 

Thanks.

### PR DESCRIPTION
**Pull request by rjoursler**
Fixes #3181.

While investigating #3181, it was found that the oneDNN GPU component had dependencies on locale through the use of `std::stringstream ` for string manipulation. These dependencies occurred for a few different reasons:

1. When generating OpenCL C code, the expected locale is `C` and passing in different locale resulted in invalid syntax due to integer formatting.
2. The ZeBin binary format encodes textual metadata in the binary. By changing the locale, the metadata becomes malformed.
3. Some GPU primitives have strategy databases stored in a human readable format. When parsing these databases, changes in the locale resulted in incorrect parsing.

This PR contains a fix for the above issues identified during manual testing.

### CODE REVIEW

**Comment by atkassen** [comment]
I think the stringstream @ src/gpu/intel/microkernels/shim.cpp:201 also needs this.

**Comment by rjoursler** [comment]
make test

**Review by atkassen — APPROVED** [review]

**Review by petercad — APPROVED** [review]

File: src/gpu/intel/jit/gemm/generator/strategy_parser.cpp [hunk 1]
```diff
@@ -520,6 +522,7 @@ void parseStrategy(const char *str, HW hw, const GEMMProblem &problem, GEMMStrat
                         strategy.slmB = true;
                     }
                     std::stringstream ms(mod);
+                    s.imbue(std::locale::classic());
```
Comment (petercad) [inline src/gpu/intel/jit/gemm/generator/strategy_parser.cpp:525]:
```suggestion
                    ms.imbue(std::locale::classic());
```

**Comment by vpirogov** [comment]
@rjoursler, could you please elaborate on what's going on here?

Related issue: https://github.com/uxlfoundation/oneDNN/issues/3181.

**Comment by atkassen** [comment]
The numbers generated for some kernels are formatted with separators when the locale is changed. The important line from the log in #3181 is
```
#define PO_0_ELTWISE_SCALE as_float(0x3f,800,000)
```
The commas should not be there.

**Comment by rjoursler** [comment]
> @rjoursler, could you please elaborate on what's going on here?

@vpirogov, I added more data to the description. At a high level, the locale dependency is due to the use `std::stringstream` for string manipulation throughout oneDNN. From my testing the only functional failures are in the Intel GPU component, but we likely need to analyze all uses of stringstream throughout the library to ensure we are not getting functional behavior via fallback implementations.

File: src/gpu/intel/jit/gemm/generator/strategy_parser.cpp (hunk 1 above)
Comment (rjoursler) [reply src/gpu/intel/jit/gemm/generator/strategy_parser.cpp]: Good catch.

**Comment by rjoursler** [comment]
make test
